### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by freeboson** [googleinterns/step125-2020#11]
Verify that the `.gitignore` file is checked in, and has the basic ignores for a Java project.

**Comment by flying-bus** [comment]
The Maven and Java templates here are good starting places:

https://stackoverflow.com/questions/51792830/what-files-in-a-maven-project-should-be-committed-to-git?answertab=votes#tab-top

**Comment by freeboson** [comment]
Here are the templates for Java and node js:

https://github.com/github/gitignore/blob/master/Java.gitignore
https://github.com/github/gitignore/blob/master/Maven.gitignore
https://github.com/github/gitignore/blob/master/Node.gitignore

You probably want to merge all of these

**Comment by TBarrett553** [comment]
Just to clarify should I make a gitignore folder and add the .gitignores above?

**Comment by flying-bus** [comment]
Sujeet can correct me if I'm wrong, but I think you want the contents of
all of those .gitignore files merged into a single .gitignore file at the
top level directory of your project.

**Comment by TBarrett553** [comment]
Ok great that makes a lot of sense. I'll do that rn!
