### ISSUE TITLE
Add continuous testing

### ISSUE THREAD

**Issue by freeboson** [googleinterns/step125-2020#14]
When you create a PR, it's extremely useful to know if it's going to break tests. GitHub supports this through "workflows". Setup a GitHub continuous testing workflow.

**Comment by freeboson** [comment]
This gets the ball rolling for maven:

https://github.com/googleinterns/step125-2020/new/master?filename=.github%2Fworkflows%2Fmaven.yml&workflow_template=maven

here's some info for jest: https://github.com/marketplace/actions/run-jest

**Comment by freeboson** [comment]
@kanbi18 I've put you in charge of getting this done, since you love testing so much :)

**Comment by kanbi18** [comment]
Sure. I could never get tired of testing code.
