### ISSUE TITLE
Move Marker serialization/deserialization into the Marker class.

### ISSUE THREAD

**Issue by flying-bus** [googleinterns/step125-2020#45]
While reviewing a couple of PRs, it seemed that we could try to clean up (and better test) some of the code by moving the code that converts markers to and from Entity objects into the Marker class as a constructor/method.

This code:
https://github.com/googleinterns/step125-2020/blob/master/maptivist/src/main/java/com/google/sps/servlets/MarkerServlet.java#L76-L84

Should become a "ToEntity()" method that creates and Entity from marker internals.

This code:
https://github.com/googleinterns/step125-2020/blob/master/maptivist/src/main/java/com/google/sps/servlets/MarkerServlet.java#L111-L120

Should become a Marker constructor that takes an Entity as an input.

That way, the code the converts to/from Entities live close to each other. Generally, if you have to modify the code that creates an Entity then you also need to modify the code that reads from the Entity - so putting them next to each other makes editing the code easier.

But more impotrantly, if we make a constructor and a method, then it's much easier to test!

```
Marker expected_marker = new Marker("title", "etc"....);
Entity serialized_marker = expected_marker.ToEntity();
Marker deserialized_maker = new Marker(serialized_marker);

Assert.assertEquals(expected_marker, deserialized_maker);
```

**Comment by TBarrett553** [comment]
That definitely makes sense. We were talking about this problem yesterday. If the UUID is created each time an entity is made into a marker, then the UUID for markers would change each time a request is made. Would this solution eliminate the problem? Essentially the marker is constructed in the post method and then turned into an Entity. Then, in the get method, the query results would be deserialized and sent back to the front end as JSON?

Please correct me if there are errors in my thinking. If not, I can maybe take on this house keeping change.

**Comment by flying-bus** [comment]
I think this would help fix the problem.

The UUID should only be created once, probably in the marker/ POST handler.

Then we can pass the UUID into the Marker object's constructor (like in PR #44), then it would get converted to the Entity automatically when it was saved in the Datastore. Then in getMarkers, it would be retrieved from the Datastore's Entity when reconstructing the Marker.

**Comment by TBarrett553** [comment]
Ok cool so there should be a toEntity method in the marker servlet or the marker class?

**Comment by flying-bus** [comment]
I would put it in the Marker class.
